name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: duck_tuto

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  jaffle_shop:
    staging:
      +materialized: view
      +meta:
        required_tests: {"unique.*|not_null": 2}
      autre:
        +tags: 'autre'
      jaffle_shop:
        +tags: 'learn'
      stripe:
        +tags: 'learn'
    intermediate:
      +materialized: table
      +tags: 'learn'
    datamarts:
      +meta:
        required_docs: true
      +materialized: table
      autre:
        +tags: 'autre'
      finance:
        +tags: 'learn'
      marketing:
        +tags: 'learn'
# dbt run -s tag:autre
# dbt run -s tag:learn
# dbt run-operation required_tests
# dbt run-operation required_docs

on-run-end:
  - "{% do grant_select(schema=target.schema, role='lecteur') %}"


### beware dbt sends warning for deactivated seeds that contains tests
# for marketing mart
seeds:
  jaffle_shop:
    +persist_docs:
      relation: true
      columns: true
    marts:
      +tags: 'learn'
    tests:
      +tags: 'tests'
# dbt seed --full-refresh -s "tag:tests"
# dbt seed --full-refresh -s "tag:learn"

vars:
  # for dbt_date
  'dbt_date:time_zone': 'Europe/Paris'
  # for staging/autre/stg_autre__orders and staging/autre/stg_autre__locations
  'truncate_timespan_to': "{{ dbt.current_timestamp() }}"

# dispatch:
#   - macro_namespace: dbt
#     search_order: ['dbt_project_evaluator', 'dbt']

# dbt build --select package:dbt_project_evaluator
# dbt build --select state:modified+ --exclude package:dbt_project_evaluator

flags:
  require_generic_test_arguments_property: true
  require_unique_project_resource_names: true

# It's important to follow the correct YAML naming conventions for the configs in your dbt_project.yml file 
# to ensure dbt can process them properly. This is especially true for resource types with more than one word.
#
# Use dashes (-) when configuring resource types with multiple words in your dbt_project.yml file.
# Use underscore (_) when configuring resource types with multiple words for YAML files other than the dbt_project.yml file.
#  ex: saved-queries (dbt_project.yml) => saved_queries (property file)